export class AppError extends Error {
  constructor(message, code, statusCode = 400, details = {}) {
    super(message);
    this.name = this.constructor.name;
    this.code = code;
    this.statusCode = statusCode;
    this.details = details;
    Error.captureStackTrace(this, this.constructor);
  }
}

export const ERROR_CODES = {
  // Auth & Session
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_TRIAL_EXPIRED: 'AUTH_TRIAL_EXPIRED',

  // Tenant / Lab
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_MODULE_DISABLED: 'TENANT_MODULE_DISABLED',
  TENANT_LIMIT_REACHED: 'TENANT_LIMIT_REACHED',

  // Clinical & Operations
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  VISIT_NOT_FOUND: 'VISIT_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  TEST_NOT_FOUND: 'TEST_NOT_FOUND',

  // Billing & Payments
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  PAYMENT_LINK_GENERATION_FAILED: 'PAYMENT_LINK_GENERATION_FAILED',
  PAYMENT_WEBHOOK_INVALID: 'PAYMENT_WEBHOOK_INVALID',

  // Validation & Integrity
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Integrations & Infrastructure
  PDF_GENERATION_FAILED: 'PDF_GENERATION_FAILED',
  WHATSAPP_DELIVERY_FAILED: 'WHATSAPP_DELIVERY_FAILED',
  STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};
